modLoader="javafml"
loaderVersion="43"
license="MIT license "
[[mods]]
modId="shutter"
version="2.0.0"
displayName="Shutter"

credits="nudelauflauch for the textures"
authors="stehschnitzel"

logoFile= "assets/shutter/textures/gui/main.png"

description='''
Adds Shutters for minecraft and different mods
'''

[[dependencies.shutter]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    side="BOTH"

[[dependencies.shutter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    side="BOTH"
